project_name: go

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

release:
  github:
    owner: mockingio
    name: mockingio

archives:
  - format_overrides:
      - goos: windows
        format: zip

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'